// import { Inter } from "next/font/google";
// import "./globals.css";
// import Hydration from "./hydration";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Hydration>{children}</Hydration>
//       </body>
//     </html>
//   );
// }

// import { Inter } from "next/font/google";
// import "./globals.css";
// import Hydration from "./hydration";
// import Head from "next/head";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <>
//       <Head>
//         {/* GTM code snippet for the <head> section */}

//       </Head>
//       <html lang="en">
//         <body className={inter.className}>
//           {/* GTM code snippet for the <body> section */}
//           <noscript>
//             <iframe
//               src="https://www.googletagmanager.com/ns.html?id=GTM-5KPDZX53"
//               height="0"
//               width="0"
//               style={{ display: "none", visibility: "hidden" }}
//             ></iframe>
//           </noscript>
//           <Hydration>{children}</Hydration>
//         </body>
//       </html>
//     </>
//   );
// }

// Assuming this is inside your RootLayout component file
import { GTMHeadScript, GTMBodyScript } from "./components/GTM/GTM"; // Adjust the path as necessary
// import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";
import Hydration from "./hydration"; // Make sure the path matches your file structure

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Other head content */}
        <title>india</title>
        <GTMHeadScript />
      </head>
      <body className={inter.className}>
        <GTMBodyScript />
        <Hydration>{children}</Hydration>
      </body>
    </html>
  );
}
